### PR TITLE
README: Added Swift example

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by CooperRS** [comment]
Hi, can you also implement a demo project using swift? That would be great! :)

**Comment by ricardopereira** [comment]
I pushed a Swift project example but when I open the selection controller it gives me: `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error: The view of an RMActionController has been loaded before a contentView has been set. You have to set the contentView before presenting a RMActionController.'`

**Comment by CooperRS** [comment]
Hi,

I took a look at the Swift demo project. The problem is that initWithStyle: is mixed up with actionControllerWithStyle:. This is rather an Apple problem than an issue with the demo project. But it can be solved by renaming initWithStyle:. I will merge your demo project after I renamed the method.

Thank you for your efforts. Really appreciate it! :)

Best regards,
Roland

**Comment by CooperRS** [comment]
While tackling some trouble properly supporting Swift, I was forced to write my own Swift Demo project in the process.

However, thank you for your efforts. It's because of you, that I thought about how to properly support Swift.

**Comment by ricardopereira** [comment]
No problem 👍 
Glad you keeping this up!

**Pull request closed without merging**
