### PR TITLE
Update podspec

### PR DESCRIPTION
**Pull request by iltercengiz**
Updated podspec file to fix missing m files.

missing_m_files

### CODE REVIEW

**Comment by CooperRS** [comment]
Which version of CocoaPods are you using?

**Comment by CooperRS** [comment]
Actually, I tried adding RMDateSelectionViewController with the original `podspec` and it worked just fine :/

**Comment by iltercengiz** [comment]
@CooperRS it's 1.1.1. I tried a second time (even reinstall), but they were missing. Besides, as far as I know, the proper way is without the spaces.

**Comment by CooperRS** [comment]
Hmm, will try myself again, when I'm home. Will let you know of the results :)

**Comment by iltercengiz** [comment]
Cool, looking forward to. :)

**Comment by CooperRS** [comment]
Hmm, you are right, the `Podfile` ist broken. Let's merge 😄

**Pull request merged**
